### PR TITLE
Confirm users on successful password recovery

### LINKED ISSUE #113: Password recovery does not confirm email
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
Added email manually, I even clicked the reset password from my email, got the "Email not confirmed" message
**- If the current behavior is a bug, please provide the steps to reproduce.**
Reset password,
Update password
Login
Logout
Login
Enter credentials
screen shot 2017-10-04 at 5 31 09 pm

**- What is the expected behavior?**
Mail works
**- Please mention your Go version, and operating system version.**
OSX Sierra

### PR DESCRIPTION
**Pull request by brycekahle**
Fixes #113

### CODE REVIEW

File: api/verify_test.go [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+
+func TestVerify(t *testing.T) {
+	suite.Run(t, new(VerifyTestSuite))
+}
+
+func (ts *VerifyTestSuite) TestVerify_PasswordRecovery() {
+	u, err := ts.API.db.FindUserByEmailAndAudience("", "test@example.com", ts.Config.JWT.Aud)
+	require.NoError(ts.T(), err)
+	u.RecoverySentAt = &time.Time{}
+	require.NoError(ts.T(), ts.API.db.UpdateUser(u))
```
Comment (rybit) [inline api/verify_test.go]: `ts.Require.NoError(ts.API.db.UpdateUser(u))` I think you can do that. For almost all of the `assert` and `require`. I think the `assert` ones even are directly available (`ts.Equal(....)`).

Comment (brycekahle) [reply api/verify_test.go]: You are correct. I mostly copied the other style. I'd rather do a PR that is just changing the asserts with no functional changes.
